name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
  obj-id:
    description: "Object ID"
    value: ${{ steps.obj-id-generator.outputs.obj-id }}
  obj-id2:
    description: "Object ID2"
    value: ${{ steps.obj-id2-generator.outputs.obj-id2 }}
  obj-date:
    description: "Object date"
    value: ${{ steps.obj-id-generator.outputs.obj-date }}
  obj-status:
    value: ${{ steps.obj-id-generator.outputs.obj-status }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8' # min version supported by Grid.ai  
    - uses: robert-s-lee/gridai_action_login@main
      with:
        username: ${{ secrets.username }} 
        key: ${{ secrets.key }}         
    - run: sudo apt-get install xterm
      shell: bash  
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
    - id: obj-id-generator
      # this step generates two outputs
      run: ${{ github.action_path }}/goodbye.sh
      shell: bash
    - id: obj-id2-generator
      run: echo "::set-output name=obj-id2::$(date +'%Y%m%d-%H%M%S')"
      shell: bash