name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
  obj-id:
    description: "Object ID"
    value: ${{ steps.obj-id-generator.outputs.obj-id }}
  obj-id2:
    description: "Object ID2"
    value: ${{ steps.obj-id2-generator.outputs.obj-id2 }}
  obj-date:
    description: "Object date"
    value: ${{ steps.obj-id-generator.outputs.obj-date }}
  obj-status:
    value: ${{ steps.obj-id-generator.outputs.obj-status }}
  obj_summary:
    value: ${{ steps.obj-id-generator.outputs.obj_summary }}
  obj_status:
    value: ${{ steps.obj-id-generator.outputs.obj_status }}        
  obj_id:
    value: ${{ steps.obj-id-generator.outputs.obj_id }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8' # min version supported by Grid.ai  
    - run: python -m pip install --upgrade pip
      shell: bash
    - run: pip install lightning-grid --upgrade
      shell: bash
    - run: |
        if [ ! -z "${{ inputs.grid_url }}" ]; then 
          export GRID_URL=${{ inputs.grid_url }}
          echo "GRID_URL=${{ inputs.grid_url }}" >> $GITHUB_ENV 
        fi
      shell: bash       
    - run: sudo apt-get install xterm
      shell: bash  
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
    - id: obj-id-generator
      # this step generates two outputs
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH; goodbye.sh
      shell: bash
    - id: obj-id2-generator
      run: echo "::set-output name=obj-id2::$(date +'%Y%m%d-%H%M%S')"
      shell: bash
    - run: | 
        # are output available to the next step
        echo obj-date ${{ steps.obj-id-generator.outputs.obj-date }}
        echo obj-status ${{ steps.obj-id-generator.outputs.obj-status }}
        echo obj_id ${{ steps.obj-id-generator.outputs.obj_id }}
        echo obj_status ${{ steps.obj-id-generator.outputs.obj_status }}   
        echo obj_summary ${{ steps.obj-id-generator.outputs.obj_summary }}         
      shell: bash
