on: [push]

jobs:
  hello_world_job:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]
    runs-on: ${{ matrix.os }}
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: foo_me
        uses: robert-s-lee/test-github-composite@main
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
      - run: echo obj-id ${{ steps.foo.outputs.obj-id }}
        shell: bash
      - run: echo obj-id2 ${{ steps.foo.outputs.obj-id2 }}
        shell: bash        
      - run: | 
          echo obj-date ${{ steps.foo_me.outputs.obj-date }}
          echo obj-status ${{ steps.foo_me.outputs.obj-status }}
          echo obj_id ${{ steps.foo_me.outputs.obj_id }}
          echo obj_status ${{ steps.foo_me.outputs.obj_status }}   
          echo obj_summary ${{ steps.foo_me.outputs.obj_summary }}          
        shell: bash                